f = open("1.txt","w")
f.write("将进酒·君不见黄河之水天上来\n")
f.write("[唐] 李白\n")
f.write("君不见黄河之水天上来，奔流到海不复回。\n")
f.write("君不见高堂明镜悲白发，朝如青丝暮成雪。\n")
f.write("人生得意须尽欢，莫使金樽空对月。\n")
f.write("天生我材必有用，千金散尽还复来。\n")
f.write("烹羊宰牛且为乐，会须一饮三百杯。\n")
f.write("岑夫子，丹丘生，将进酒，杯莫停。\n")
f.write("与君歌一曲，请君为我侧耳听。\n")
f.write("钟鼓馔玉不足贵，但愿长醉不复醒。\n")
f.write("古来圣贤皆寂寞，惟有饮者留其名。\n")
f.write("陈王昔时宴平乐，斗酒十千恣欢谑。\n")
f.write("主人何为言少钱，径须沽取对君酌。\n")
f.write("五花马，千金裘，\n")
f.write("呼儿将出换美酒，与尔同销万古愁。\n")
f.close()
f1 = open("1.txt","r")
c = f1.readlines()
'''
f2 = open("1.txt","w")
for i in c:
    s = i[:len(i)-1]
        f2.write(s + "*_*\n")
f1.close()
f2.close()
'''
